#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
source "$script_dir/lib.sh"

run_scenario_test lib identity_collision
run_scenario_test lib live_photo_motion_with_size_suffixed_primary_stem_is_on_disk_skipped
run_scenario_test lib live_photo_motion_with_identity_suffixed_primary_stem_is_on_disk_skipped
run_scenario_test lib live_photo_motion_with_sanitized_identity_suffix_is_on_disk_skipped
run_scenario_test lib live_photo_motion_original_policy_with_primary_collision_is_on_disk_skipped
run_scenario_test lib import_matches_live_photo_motion_from_size_suffixed_primary_stem
run_scenario_test lib import_matches_live_photo_motion_from_sanitized_identity_suffixed_primary_stem
run_scenario_test lib pending_same_size_collision_does_not_adopt_other_assets_bare_file
run_scenario_test lib truncated_suffixed_downloaded_file_is_forwarded_not_on_disk_skipped
