#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
source "$script_dir/lib.sh"

run_scenario_test lib incremental_multi_album_unfiled_uses_membership_without_album_enumeration
run_scenario_test lib incremental_expired_urls_are_refreshed_and_retried_same_cycle
run_scenario_test lib incremental_preflight_refreshes_aged_urls_before_first_download
run_scenario_test lib incremental_expired_url_retry_hydrates_instead_of_replaying_stale_delta
run_scenario_test lib incremental_expired_url_retry_hydrates_relation_only_album_assets
run_scenario_test lib pending_retry_expired_url_hydrates_current_records
